# <registry>/ubuntu:18.04-zh
FROM ubuntu:18.04

ADD ./sources.list /etc/apt/sources.list

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y ca-certificates \
    && apt-get install -y apt-utils \
    && apt-get install -y wget \
    && apt-get install -y jq \
    && apt-get install -y language-pack-zh-hans language-pack-zh-hans-base \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y locales \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* \
    && rm -rf /var/lib/apt/lists/*

RUN echo "Asia/Shanghai" | tee /etc/timezone && \
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

RUN echo en_US.UTF-8 zh_CN.UTF-8 UTF-8 >> /etc/locale.gen && \
    locale-gen && \
    update-locale LC_ALL=zh_CN.UTF-8 LANG=zh_CN.UTF-8
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh